application:
  port: 8000
database:
  host: 'localhost'
  port: 5454
  username: 'postgres'
  password: 'postgres'
  database_name: 'newsletter'
email_client:
  base_url: "https://api.postmark.com"
  sender_email: "kyle.mazeika@beckshybrids.com"